[book]
title = "MatrixOne 中文手册"
authors = ["MatrixOne"]
description = "The MatrixOne product documentation."
language = "zh"
src = "."

[rust]
edition = "2021"

[build]
build-dir = "./book"
create-missing = false

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
