name: ci
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Document Version'
        required: true
        default: '0.3.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.ACTIONTOKEN }}
          submodules: true

      - name: build image
        run: |
          cd scripts 
          && ./upgrade.sh ${{ github.event.inputs.version }} ${{ secrets.DOCKERHUBPASSWORD }} 
