name: lint

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: 
      - '*'
  workflow_dispatch:

jobs:
  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Enable pnpm as package manager
      run: corepack enable

    - name: Install dependencies
      run: pnpm i --frozen-lockfile

    - name: Lint Markdown files
      run: pnpm exec lint
